Updated licensing information.
SymbiFlow/vtr-xml-utils pull request #10
Opened 2020-04-21 12:07 UTC by mkurc-ant

Signed-off-by: Maciej Kurc <mkurc@antmicro.com>

2020-04-21 22:53 UTC, mithro commented on LICENSE
> +Copyright (C) 2019  SymbiFlow Project Authors.
Expand copyright date.

2020-04-22 00:04 UTC, mithro requested changes
Please go through the checklist at https://github.com/SymbiFlow/ideas/issues/47 and make sure everything is covered then re-request review.

2020-04-22 00:04 UTC, mithro commented on setup.py
> +#
Please use the short form of the ISC license header

2020-04-22 00:04 UTC, mithro commented on setup.py
> +#
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
```

2020-04-22 00:04 UTC, mithro commented on vtr_xml_utils/__main__.py
> +#
Extra `#` at the end.

2020-04-22 00:04 UTC, mithro commented on vtr_xml_utils/resources/convert-pb_type-attributes.xsl
> +
Extra newline here.

2020-04-22 00:28 UTC, daniellimws commented
The files inside https://github.com/SymbiFlow/vtr-xml-utils/tree/master/tests don't have the headers yet.

2020-04-22 07:38 UTC, mkurc-ant commented on LICENSE
> +Copyright (C) 2019  SymbiFlow Project Authors.
Fixed

2020-04-22 07:38 UTC, mkurc-ant commented on setup.py
> +#
Fixed

2020-04-22 07:39 UTC, mkurc-ant commented on vtr_xml_utils/__main__.py
> +#
Removed

2020-04-22 07:39 UTC, mkurc-ant commented on vtr_xml_utils/resources/convert-pb_type-attributes.xsl
> +
Removed

2020-04-22 07:39 UTC, mkurc-ant commented on setup.py
> +#
Changed everywhere

2020-04-22 07:40 UTC, mkurc-ant commented
@daniellimws Added the license header to the test script
@mithro Should all xml files under the test directory also have a license? These are just data files for the tests.

2020-04-25 01:58 UTC, daniellimws commented
There's also this in the checklist.

- [ ] Add or update the AUTHORS files to have the text as shown at https://opensource.google/docs/releasing/authors/

2020-04-28 14:01 UTC, mkurc-ant commented
@daniellimws I've added the `AUTHORS` file.

2020-04-28 14:03 UTC, daniellimws commented on AUTHORS
> +s is the list of vtr-xml-utils' significant contributors.
`This`?

2020-04-28 14:14 UTC, mkurc-ant commented on AUTHORS
> +s is the list of vtr-xml-utils' significant contributors.
Yep... Fixed.

2020-06-24 06:27 UTC, daniellimws requested changes

2020-06-24 06:27 UTC, daniellimws commented on AUTHORS
> +This is the list of vtr-xml-utils' significant contributors.
`# This is ...`

2020-06-24 08:57 UTC, daniellimws approved these changes

2020-06-25 01:48 UTC, daniellimws commented
@mithro Looks like this can be merged already

2020-12-03 17:11 UTC, litghost commented
Please rebase on master

2020-12-07 15:28 UTC, mkurc-ant commented
@litghost @mithro Rebased.

2020-12-07 16:57 UTC, mithro approved these changes
LGTM!

2020-12-07 16:57 UTC, merged